#!/bin/bash

ask() { local q="$1"; local d=${2:-"n"}
  read -p "$q [$d]: " r; r=${r:-"$d"}
  local i=0; while true; do
    case $r in
      y|Y|yes|Yes|yES|YES )
        return 0
        ;;
      n|N|no|No|nO )
        return 1
        ;;
      * )
        i=$((i+1))
        [ $i -le 3 ] && read -p "Not a valid answer. Try 'y' or 'n': " r || exit 1
        continue
        ;;
    esac
  done
}

workdir=$(dirname $(realpath `dirname $0`)); err=0
echo "This script will pull sources from git and update Ubuntu-WRT."
echo "Sources will be pulled within the parent directory: $workdir"
if ! ask "Do you wish to continue?" "y"; then exit 0; fi

echo -e "\nPlease, select the distribution you wish to update:"
echo "1) all"

s=1; opts=""; for d in $(realpath `dirname $0`)/ubuntu-*; do
  distro=$(basename $d)
  s=$((s+1))
  echo "$s) $distro"
  opts="$opts;$s,$distro"
done; unset distro; unset s

read -p "Distribution [1]: " d; [ -z $d ] && d="1"

t=0; while true; do

  if [ $d -eq 1 ]; then
    distro="all"
    break
  fi

  for i in $(echo $opts | sed "s/;/ /g"); do
    o=`echo $i | cut -d ',' -f1`
    if [ $d = $o ]; then
      distro=`echo $i | cut -d ',' -f2`
      break
    fi
  done

  if [ -z "$distro" ]; then
    t=$((t+1)); [ $t -gt 3 ] && echo "Too many times. Quitting." && exit 1
    read -p "$d is not a valid option. Try again: " d
    continue
  fi

  break

done; unset t
echo

update() { local distro="$1"
# mwlwifi
cd "$workdir"; echo "Updating mwlwifi... "
[ ! -d ./mwlwifi ] && git clone https://github.com/kaloz/mwlwifi.git
if cd mwlwifi; then
  git pull; cd ..
  if rm -rf ubuntu-wrt/$distro/drivers/mwlwifi; then
    cp -r mwlwifi ubuntu-wrt/$distro/drivers/
    rm -rf ubuntu-wrt/$distro/drivers/mwlwifi/.git
    mv -f ubuntu-wrt/$distro/drivers/mwlwifi/Makefile.kernel ubuntu-wrt/$distro/drivers/mwlwifi/Makefile
    # update firmware
    rm -rf ubuntu-wrt/$distro/firmware/mwlwifi
    mv ubuntu-wrt/$distro/drivers/mwlwifi/bin/firmware ubuntu-wrt/$distro/firmware/mwlwifi
    rm -rf ubuntu-wrt/$distro/drivers/mwlwifi/bin
  else
    echo "mwlwifi driver missing. Maybe not right branch?"
  fi
else
  echo "Failed to clone mwlwifi."
  err=$((err+1))
fi

# mwifiex
cd "$workdir"; echo "Updating mwifiex firmware... "
[ ! -d ./linux-firmware ] && git clone git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
if cd linux-firmware; then
  git pull; cd ..
  if rm -f ubuntu-wrt/$distro/firmware/mrvl/*; then
    cp -f linux-firmware/mrvl/sd8887_uapsta.bin ubuntu-wrt/$distro/firmware/mrvl/sd8887_uapsta.bin
  else
    echo "mwifiex firmware missing. Maybe not right branch?"
  fi
else
  echo "Failed to clone linux-firmware."
  err=$((err+10))
fi

# cake
cd "$workdir"; echo "Updating sch_cake... "
[ ! -d ./sch_cake ] && git clone https://github.com/dtaht/sch_cake.git
if cd sch_cake; then
  git pull; cd ..
  cp -f sch_cake/*.c sch_cake/*.h ubuntu-wrt/$distro/net/sched/
else
  echo "Failed to clone sch_cake."
  err=$((err+100))
fi

# wireless-regdb
cd "$workdir"; echo "Updating wireless-regdb... "
[ ! -d ./wireless-regdb ] && git clone git://git.kernel.org/pub/scm/linux/kernel/git/linville/wireless-regdb.git
if cd wireless-regdb; then
  git pull; cd ..
  cp -f wireless-regdb/db.txt ubuntu-wrt/$distro/net/wireless/db.txt
else
  echo "Failed to clone wireless-regdb."
  err=$((err+1000))
fi

cd "$workdir"
if [ $err = 0 ]; then
  if ask "Done. Do you wish to run ubuntu-wrt ./merge to update $distro sources?" "n"; then
    [ -d "$workdir/$distro" ] &&\
    ubuntu-wrt/merge -s ubuntu-wrt/$distro -t $distro -i ||\
    echo "$workdir/$distro does not exist."
  fi
  echo
else
  echo "There have been errors during update."
  exit $err
fi
}

if [ "$distro" = "all" ]; then
  for d in $(realpath `dirname $0`)/ubuntu-*; do
    distro=$(basename $d)
    echo "Updating $distro... "
    update "$distro"
  done
else
  update "$distro"
fi
