#!/bin/bash

ask() { local q="$1"; local d=${2:-"n"}
  read -p "$q [$d]: " r; r=${r:-"$d"}
  local i=0; while true; do
    case $r in
      y|Y|yes|Yes|yES|YES )
        return 0
        ;;
      n|N|no|No|nO )
        return 1
        ;;
      * )
        i=$((i+1))
        [ $i -le 3 ] && read -p "Not a valid answer. Try 'y' or 'n': " r || exit 1
        continue
        ;;
    esac
  done
}

workdir=$(dirname $(realpath `dirname $0`)); err=0
distro="linux-stable"
echo "This script will pull sources from git and update Ubuntu-WRT."
echo "Sources will be pulled within the parent directory: $workdir"
if ! ask "Do you wish to continue?" "y"; then exit 0; fi

# mwlwifi
cd "$workdir"; echo "Updating mwlwifi... "
[ ! -d ./mwlwifi ] && git clone https://github.com/kaloz/mwlwifi.git
if cd mwlwifi; then
  git pull; cd ..
  if rm -rf ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi; then
    cp -r mwlwifi ubuntu-wrt/$distro/drivers/net/wireless/marvell/
    rm -rf ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/.git
    mv -f ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/Makefile.kernel ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/Makefile
    rm -rf ubuntu-wrt/$distro/drivers/net/wireless/marvell/mwlwifi/bin
    cd ubuntu-wrt/$distro
    # Apply vfs_write -> kernel_write patch
    if ask "Do you wish to apply the vfs_write patch for mwlwifi and kernel >= 4.14?" "y"; then
      echo "Applying vfs_write -> kernel_write patch to mwlwifi... "
      sed -i 's/vfs_write/kernel_write/g' drivers/net/wireless/marvell/mwlwifi/debugfs.c
    fi
    # Apply regfree patches
    if ask "Do you wish to apply regfree patch for mwlwifi?" "y"; then
      echo "Applying regfree patch to mwlwifi... "
      wget -q https://raw.githubusercontent.com/ValCher1961/McDebian_WRT3200ACM/master/kernel-4.14.X/patch.regfree -O - | cat - | patch -p1
    fi
  else
    echo "mwlwifi driver missing. Maybe not right branch?"
  fi
else
  echo "Failed to clone mwlwifi."
  err=$((err+1))
fi

# mwifiex firmware
cd "$workdir"; echo "Updating mwifiex firmware... "
[ ! -d ./linux-firmware ] && git clone git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
if cd linux-firmware; then
  git pull; cd ..
else
  echo "Failed to clone linux-firmware."
  err=$((err+10))
fi

# cake
cd "$workdir"; echo "Updating sch_cake... "
[ ! -d ./sch_cake ] && git clone https://github.com/dtaht/sch_cake.git
if cd sch_cake; then
  git pull; cd ..
  cp -f sch_cake/*.c sch_cake/*.h ubuntu-wrt/$distro/net/sched/
else
  echo "Failed to clone sch_cake."
  err=$((err+100))
fi

# wireless-regdb
cd "$workdir"; echo "Updating wireless-regdb... "
[ ! -d ./wireless-regdb ] && git clone git://git.kernel.org/pub/scm/linux/kernel/git/linville/wireless-regdb.git
if cd wireless-regdb; then
  git pull; cd ..
  cp -f wireless-regdb/db.txt ubuntu-wrt/$distro/net/wireless/db.txt
else
  echo "Failed to clone wireless-regdb."
  err=$((err+1000))
fi

cd "$workdir"
if [ $err = 0 ]; then
  if ask "Done. Do you wish to run ubuntu-wrt ./merge to update $distro sources?" "n"; then
    [ -d "$workdir/$distro" ] &&\
    ubuntu-wrt/merge -s ubuntu-wrt/$distro -t $distro -i ||\
    echo "$workdir/$distro does not exist."
  fi
  echo
  echo "Starting from kernel 4.14, firmware is no longer included in tree and it is not installed by make modules_install anymore."
  echo "You should install manually from linux-firmware repository (mwifiex: linux-firmware/mrvl/sd8887_uapsta.bin) and mwlwifi (mwlwifi/bin/firmware/*.bin)."
  echo
else
  echo "There have been errors during update."
  exit $err
fi
